# Generated by Django 4.2.8 on 2024-02-01 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import matches.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=255)),
                ('po_type', models.CharField(choices=[('NULL', 'No Play Off (Regular Game)'), ('Q', 'Qualification Round'), ('QF', 'Quarterfinals'), ('SF', 'Semifinals'), ('B', 'Bronze Medal Game'), ('F', 'Finals')], default='NULL', max_length=4)),
                ('team1short', models.CharField(max_length=255)),
                ('team2short', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('score', models.JSONField(default=matches.models.Game.default_score)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1bet', models.PositiveIntegerField()),
                ('team2bet', models.PositiveIntegerField()),
                ('team1status', models.CharField(choices=[('REGULAR', 'Regular'), ('OVERTIME', 'Overtime'), ('SHOOTOUT', 'Shootout')], default='REGULAR', max_length=8)),
                ('team2status', models.CharField(choices=[('REGULAR', 'Regular'), ('OVERTIME', 'Overtime'), ('SHOOTOUT', 'Shootout')], default='REGULAR', max_length=8)),
                ('bet_status', models.CharField(choices=[('placed', 'Placed'), ('win', 'Win'), ('lose', 'Lose'), ('push', 'Push'), ('none', 'The bet was not placed until the start of the match')], default='placed', max_length=6)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
