# Generated by Django 5.0.2 on 2024-03-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='team1bet',
            new_name='team1_bet',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='team1status',
            new_name='team1_status',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='team2bet',
            new_name='team2_bet',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='team2status',
            new_name='team2_status',
        ),
        migrations.AddField(
            model_name='bet',
            name='bet_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bet',
            name='team1_result',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bet',
            name='team2_result',
            field=models.IntegerField(default=0),
        ),
    ]
