# Generated by Django 4.2.8 on 2024-02-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='po_type',
            field=models.CharField(choices=[('null', 'No Play Off (Regular Game)'), ('Q', 'Qualification Round'), ('QF', 'Quarterfinals'), ('SF', 'Semifinals'), ('B', 'Bronze Medal Game'), ('F', 'Finals')], default='null', max_length=4),
        ),
    ]
