# Generated by Django 4.2.8 on 2024-02-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_game_po_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='po_type',
            field=models.CharField(blank=True, choices=[('null', 'No Play Off (Regular Game)'), ('Q', 'Qualification Round'), ('QF', 'Quarterfinals'), ('SF', 'Semifinals'), ('B', 'Bronze Medal Game'), ('F', 'Finals')], max_length=4, null=True),
        ),
    ]
