# Generated by Django 4.2.8 on 2024-02-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_of', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestof',
            name='best_points',
            field=models.CharField(max_length=100),
        ),
    ]
