# Generated by Django 5.0.2 on 2024-03-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_of', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestof',
            name='tournament_winner',
            field=models.CharField(choices=[('Švédsko', 'Švédsko'), ('Francúzsko', 'Francúzsko'), ('Fínsko', 'Fínsko'), ('Česko', 'Česko'), ('Slovensko', 'Slovensko'), ('Veľká Británia', 'Veľká Británia'), ('Nórsko', 'Nórsko'), ('Lotyšsko', 'Lotyšsko'), ('Nemecko', 'Nemecko'), ('Rakúsko', 'Rakúsko'), ('Dánsko', 'Dánsko'), ('Kazachstan', 'Kazachstan'), ('USA', 'USA'), ('Kanada', 'Kanada'), ('Poľsko', 'Poľsko'), ('Švajčiarsko', 'Švajčiarsko')], max_length=100),
        ),
    ]
